version: "3.9"
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    image: mysql:latest

  node1:
    build: .
    environment:
      - API_ENABLED=on
      - ARTERY_HOST=node1
      - ARTERY_PORT=2551
      - SEED1_HOST=node1
      - SEED1_PORT=2551
      - SEED2_HOST=node2
      - SEED2_PORT=2552
      - DB_HOST=mysql
    ports:
      - "8081:8080"

  node2:
    build: .
    environment:
      - ARTERY_HOST=node2
      - ARTERY_PORT=2552
      - SEED1_HOST=node1
      - SEED1_PORT=2551
      - SEED2_HOST=node2
      - SEED2_PORT=2552
      - DB_HOST=mysql
