version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    deploy:
      placement:
        constraints:
          - node.labels.host==beelink1

  node1:
    image: beelink1:5000/sea-battle:latest
    environment:
      - API_ENABLED=on
      - ARTERY_HOST=node1
      - ARTERY_PORT=2551
      - SEED1_HOST=node1
      - SEED1_PORT=2551
      - SEED2_HOST=node2
      - SEED2_PORT=2552
      - DB_HOST=mysql
      - HEALTH_PORT=8558
    ports:
      - 8080:8080
#      - 8558:8558
    healthcheck:
      test: curl -sS http://127.0.0.1:8558/ready || echo 1
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.labels.host==beelink1
        replicas: 1
#        update_config:
#          parallelism: 1
#          order: start-first
#          failure_action: rollback
#          delay: 3s
#        rollback_config:
#          parallelism: 0
#          order: stop-first
#        restart_policy:
#          condition: any
#          delay: 5s
#          max_attempts: 3
#          window: 30s

  node2:
    image: beelink1:5000/sea-battle:latest
#    ports:
#      - 8559:8558
    environment:
      - ARTERY_HOST=node2
      - ARTERY_PORT=2552
      - SEED1_HOST=node1
      - SEED1_PORT=2551
      - SEED2_HOST=node2
      - SEED2_PORT=2552
      - DB_HOST=mysql
      - HEALTH_PORT=8558
    healthcheck:
      test: curl -sS http://127.0.0.1:8558/ready || echo 1
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.labels.host==beelink2
